[package]
name = "kvs"
version = "0.1.0"
edition = "2024"
authors=["terry"]
description = "A key-value store"
[dependencies]
clap = { version = "4.5.53", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
